name: Notification Saturday

on:
  # schedule:
    # At 13:19 AM on the each day of the month, Moscow time (UTC+3)
    # Cron times are in UTC so adjust accordingly: 9 AM UTC+3 is 6 AM UTC
    # - cron: '19 10 * * 6'
  workflow_dispatch:
      
jobs:
  notification-disc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Send notification
      env:
        DISC: ${{ secrets.DISC }}
      run: |
        curl -F "payload_json={\"content\": \"ðŸ“š Today 14:40 \"}" \
             $DISC
             
  notification-tam:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4       
    - name: TamTam
      env:
        TOKEN:   ${{ secrets.TAM }}
        CHAT_ID: ${{ secrets.TAM_CHAT }}
      run: |
        curl -X POST \
               "https://botapi.tamtam.chat/messages?access_token=$TOKEN&chat_id=$CHAT_ID" \
               -H "Content-Type: application/json" \
               -d '{
                    "disable_link_preview": false,
                    "text": "ðŸ“š Today 14:40 ",
                    "format": "markdown"
                   }'
                   
  notification-max:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Max
      env:
        TOKEN:   ${{ secrets.MAX }}
        CHAT_ID: ${{ secrets.MAX_CHAT }}
      run: |
        curl -X POST \
               "https://botapi.max.ru/messages?access_token=$TOKEN&chat_id=$CHAT_ID" \
               -H "Content-Type: application/json" \
               -d '{
                    "disable_link_preview": false,
                    "text": "ðŸ“š Today 14:40 ",
                    "format": "markdown"
                   }'
